name: eAgency
favicon: null
layout_spectrum: 0.15809689997695386
typography_spectrum: 0.15602131863124669
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.01798574300482869
  lightness: 0.4980021060910076
  saturation: 0.9790843608789146
  rhythmicContrast: 0.8713461773004383
purpose: []
